apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    securityContext:
      privileged: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000
      runAsGroup: 1000

